function [fitresult, gof] = createGaussYExpFit()
%CREATEFIT(SHORTLATTICEHOLDVECTOR,SHORTGAUSSATOMNUMBER_YVECTOR)

close(figure(78));
load('.\atomdata');
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : shortLatticeHoldVector
%      Y Output: shortGaussAtomNumber_yVector
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Mar-2021 22:35:40
for ii=1:length(atomdata) LatticeHoldVector(ii)=atomdata(ii).vars.LatticeHold; end
for ii=1:length(atomdata) GaussAtomNumber_yVector(ii)=atomdata(ii).gaussAtomNumber_y; end
StartData=10;
EndData=19;
shortLatticeHoldVector=LatticeHoldVector(StartData:EndData);
shortGaussAtomNumber_yVector = GaussAtomNumber_yVector(StartData:EndData);



%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( shortLatticeHoldVector, shortGaussAtomNumber_yVector );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [38000.1414485777 -0.00174051435226457];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure(78);
h = plot( fitresult, xData, yData );
legend( h, 'shortGaussAtomNumber_yVector vs. shortLatticeHoldVector', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'shortLatticeHoldVector', 'Interpreter', 'none' );
ylabel( 'shortGaussAtomNumber_yVector', 'Interpreter', 'none' );
grid on


