function [fitresult, gof] = kickedAA_decayFit(t, y, options)
%CREATEFIT(T,Y)
%  Create a fit.
%
%  Data for 'kickedAA_decayRateFit' fit:
%      X Input : t
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

arguments
    t double
    y double
end
arguments
   options.ExcludedIndices double = []
end

%  Auto-generated by MATLAB on 09-Apr-2021 13:18:05


%% Fit: 'kickedAA_decayRateFit'.
[xData, yData] = prepareCurveData( t, y );

% Set up fittype and options.
ft = fittype( 'exp1' );
excludedPoints = excludedata( xData, yData, 'Indices', options.ExcludedIndices );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 -Inf];
opts.Robust = 'Bisquare';
% opts.Robust = 'LAR';
opts.StartPoint = [29618.0867505899 -0.000462330123134109];
opts.Upper = [Inf 0];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'kickedAA_decayRateFit' );
% h = plot( fitresult, xData, yData, excludedPoints );
% legend( h, 'y vs. t', 'Excluded y vs. t', 'kickedAA_decayRateFit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 't', 'Interpreter', 'none' );
% ylabel( 'y', 'Interpreter', 'none' );
% grid on


